name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy HTML to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      run: |
        # Create SSH key file
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        
        # Get instance DNS and update HTML
        INSTANCE_DNS="${{ secrets.SSH_HOST }}"
        CURRENT_TIME=$(date '+%Y-%m-%d %H:%M:%S UTC')
        
        # Replace placeholders in HTML
        sed -i "s/INSTANCE_DNS_PLACEHOLDER/$INSTANCE_DNS/g" index.html
        sed -i "s/AUTO_UPDATE_TIME/$CURRENT_TIME/g" index.html
        
        # Copy updated HTML to EC2 and restart httpd
        scp -o StrictHostKeyChecking=no -i private_key index.html ${SSH_USERNAME}@${SSH_HOST}:/tmp/
        
        ssh -o StrictHostKeyChecking=no -i private_key ${SSH_USERNAME}@${SSH_HOST} "
          # Backup current file
          sudo cp /var/www/html/index.html /var/www/html/index.html.backup.\$(date +%s)
          
          # Copy new file
          sudo cp /tmp/index.html /var/www/html/
          
          # Set permissions
          sudo chown apache:apache /var/www/html/index.html
          sudo chmod 644 /var/www/html/index.html
          
          # Reload httpd service
          sudo systemctl reload httpd
          
          # Verify deployment
          if curl -f -s http://localhost > /dev/null; then
            echo '✅ Deployment successful'
          else
            echo '❌ Deployment failed'
            exit 1
          fi
        "
        
        # Cleanup
        rm -f private_key

    - name: Verify deployment
      run: |
        echo "🎉 Deployment completed!"
        echo "🌐 Check your site at: http://${{ secrets.SSH_HOST }}"
        echo "🕒 Last updated at: $(date '+%Y-%m-%d %H:%M:%S UTC')"